import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import '../../core/colors.dart';
import '../../core/validators.dart';
import '../../services/auth_service.dart';
import '../../widgets/brand_text_field.dart';
import '../home_screen.dart';

/// Sign up screen: branded header, live password strength checklist,
/// confirm-password hint, and a Terms/Privacy consent checkbox.
class SignUpScreen extends StatefulWidget {
  const SignUpScreen({super.key});

  @override
  State<SignUpScreen> createState() => _SignUpScreenState();
}

// Condensed placeholder legal text. Replace with reviewed copy (and fill in
// the [DATE] / [CONTACT EMAIL] placeholders) before publishing.
const _termsOfServiceText = '''
MaisNutri is a corn leaf nutrient deficiency detection tool developed by Ma. Christina P. Beltran, Joana Mae E. Zipagan, Mary Rose G. Talosig, and Cecille M. Darantan as part of an undergraduate thesis at Isabela State University, Cabagan Campus. By using the app you agree to these Terms.

License
The Application is provided for research and field-testing purposes as part of an academic thesis project.

Intellectual Property
The Service Provider retains all rights in the app's code, trained models, and branding.

Account and Age
You must be legally permitted to use the app in your jurisdiction. Below the minimum age of digital consent, a parent or guardian must accept these Terms on your behalf.

Corn Leaf Detection Results
Nutrient deficiency detections and fertilizer recommendations are generated by an automated model and are intended to support, not replace, professional agricultural advice.

Limitation of Liability
The Service Provider is not liable for crop management decisions made based on the app's output.

Termination
The Service Provider may suspend or terminate access for misuse of the Application.

Governing Law
These Terms are governed by the laws of the Republic of the Philippines.

Changes
The Service Provider may update these Terms and will post the new version here.

Effective [DATE]. Contact: [CONTACT EMAIL]
''';

const _privacyPolicyText = '''
This policy applies to the MaisNutri app, developed by the thesis research team at Isabela State University, Cabagan Campus (the "Service Provider").

Information Collected
Corn leaf photos you capture or upload, your account name and email, and, if you choose to enable it, the location and date associated with each diagnosis.

How It's Used
To run on-device nutrient deficiency detection, generate fertilizer recommendations, and maintain your diagnosis history.

Third-Party Sharing
Captured leaf images and diagnosis results are not shared with third parties. Data collected during this research may be used in anonymized form for thesis evaluation only.

Your Rights
You may request access to, correction of, or deletion of your account data by contacting [CONTACT EMAIL].

Data Retention
Diagnosis history is kept in your account until you delete it or ask us to remove it.

Children
The app is not intended for children under the applicable minimum age.

Security
Account credentials and diagnosis history are stored using industry-standard safeguards.

Changes
The Service Provider may update this policy and will notify you of material changes.

Effective [DATE]. Contact: [CONTACT EMAIL]
''';

class _SignUpScreenState extends State<SignUpScreen> {
  final AuthService _auth = const AuthService();

  final fullNameController = TextEditingController();
  final emailController = TextEditingController();
  final passwordController = TextEditingController();
  final confirmController = TextEditingController();

  bool isLoading = false;
  bool agreedToTerms = false;
  bool _obscurePassword = true;
  bool _obscureConfirm = true;

  // Inline error messages
  String? _fullNameError;
  String? _emailError;
  String? _passwordError;
  String? _confirmError;
  String? _termsError;

  @override
  void initState() {
    super.initState();

    // Rebuild on every keystroke so the eye icons, password checklist,
    // confirm-match hint, and live email hint stay in sync as the user types.
    for (final controller in [
      fullNameController,
      emailController,
      passwordController,
      confirmController,
    ]) {
      controller.addListener(() => setState(() {}));
    }
  }

  // Live email format hint shown while typing, before the user submits.
  String? get _liveEmailError {
    final email = emailController.text.trim();
    if (email.isEmpty) return null;
    return Validators.email(email);
  }

  // Individual password checks, reused by isStrongPassword and the live
  // requirements checklist so both stay in sync.
  bool _hasMinLength(String p) => p.length >= 8;
  bool _hasUpper(String p) => RegExp(r'[A-Z]').hasMatch(p);
  bool _hasLower(String p) => RegExp(r'[a-z]').hasMatch(p);
  bool _hasDigit(String p) => RegExp(r'\d').hasMatch(p);
  bool _hasSpecial(String p) =>
      RegExp(r'''[!@#$%^&*()_+\-=\[\]{};'\\:"|<>?,./`~]''').hasMatch(p);

  bool isStrongPassword(String password) {
    return _hasMinLength(password) &&
        _hasUpper(password) &&
        _hasLower(password) &&
        _hasDigit(password) &&
        _hasSpecial(password);
  }

  bool _validate() {
    final fullName = fullNameController.text.trim();
    final email = emailController.text.trim();
    final password = passwordController.text.trim();
    final confirm = confirmController.text.trim();

    setState(() {
      _fullNameError = fullName.isEmpty ? 'Full name is required.' : null;
      _emailError = email.isEmpty
          ? 'Email is required.'
          : Validators.email(email);

      if (password.isEmpty) {
        _passwordError = 'Password is required.';
      } else if (!isStrongPassword(password)) {
        _passwordError =
            'Password must contain at least 8 characters, including an '
            'uppercase letter, a lowercase letter, a number, and a special '
            'character.';
      } else {
        _passwordError = null;
      }

      if (confirm.isEmpty) {
        _confirmError = 'Please confirm your password.';
      } else if (confirm != password) {
        _confirmError = 'Passwords do not match.';
      } else {
        _confirmError = null;
      }

      _termsError = agreedToTerms
          ? null
          : 'You must agree to the Terms and Privacy Policy.';
    });

    return _fullNameError == null &&
        _emailError == null &&
        _passwordError == null &&
        _confirmError == null &&
        _termsError == null;
  }

  Future<void> signUp() async {
    if (!_validate()) return;
    if (isLoading) return;

    setState(() => isLoading = true);

    try {
      final signedIn = await _auth.signUp(
        fullName: fullNameController.text.trim(),
        email: emailController.text.trim(),
        password: passwordController.text,
      );
      if (!mounted) return;

      if (signedIn) {
        Navigator.pushAndRemoveUntil(
          context,
          MaterialPageRoute(builder: (_) => const HomeScreen()),
          (route) => false,
        );
      } else {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text(
              'Check your email to confirm your account, then log in.',
            ),
          ),
        );
      }
    } on AuthException catch (e) {
      if (mounted) setState(() => _emailError = e.message);
    } catch (e) {
      if (mounted) {
        setState(() => _emailError = 'Something went wrong. Please try again.');
      }
    }

    if (mounted) setState(() => isLoading = false);
  }

  // Shows placeholder legal text in a dialog. Replace with real copy.
  void _showLegalDialog(String title, String body) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(title),
        content: SingleChildScrollView(child: Text(body)),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text(
              'Close',
              style: TextStyle(color: AppColors.brandGreen),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SingleChildScrollView(
        child: ConstrainedBox(
          constraints: BoxConstraints(
            minHeight: MediaQuery.of(context).size.height,
          ),
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 30),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const SizedBox(height: 60),

                Image.asset(
                  'assets/images/logo.png',
                  height: 120,
                  errorBuilder: (context, error, stackTrace) => const Icon(
                    Icons.eco,
                    size: 100,
                    color: AppColors.brandGreen,
                  ),
                ),

                const SizedBox(height: 10),

                const Text(
                  'MaisNutri',
                  style: TextStyle(
                    fontSize: 32,
                    fontWeight: FontWeight.bold,
                    color: AppColors.brandGreen,
                  ),
                ),

                const SizedBox(height: 8),

                const Text(
                  'Scan corn leaves. Detect deficiencies.\n'
                  'Grow healthier crops.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 12,
                    color: AppColors.brandGreen,
                    height: 1.4,
                  ),
                ),

                const SizedBox(height: 40),

                BrandTextField(
                  hint: 'Full Name',
                  controller: fullNameController,
                  error: _fullNameError,
                  onChanged: () => setState(() => _fullNameError = null),
                ),

                const SizedBox(height: 15),

                BrandTextField(
                  hint: 'Email',
                  controller: emailController,
                  keyboardType: TextInputType.emailAddress,
                  error: _emailError ?? _liveEmailError,
                  onChanged: () => setState(() => _emailError = null),
                ),

                const SizedBox(height: 15),

                BrandTextField(
                  hint: 'Password',
                  controller: passwordController,
                  isPassword: true,
                  obscureText: _obscurePassword,
                  onToggleObscure: () =>
                      setState(() => _obscurePassword = !_obscurePassword),
                  error: passwordController.text.isEmpty
                      ? _passwordError
                      : null,
                  onChanged: () => setState(() => _passwordError = null),
                ),
                _buildPasswordChecklist(),

                const SizedBox(height: 15),

                BrandTextField(
                  hint: 'Confirm Password',
                  controller: confirmController,
                  isPassword: true,
                  obscureText: _obscureConfirm,
                  onToggleObscure: () =>
                      setState(() => _obscureConfirm = !_obscureConfirm),
                  error: confirmController.text.isEmpty ? _confirmError : null,
                  onChanged: () => setState(() => _confirmError = null),
                ),
                _buildConfirmHint(),

                const SizedBox(height: 20),

                _buildTermsCheckbox(),

                const SizedBox(height: 25),

                SizedBox(
                  width: double.infinity,
                  height: 50,
                  child: ElevatedButton(
                    onPressed: isLoading ? null : signUp,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.brandGreen,
                      disabledBackgroundColor: AppColors.brandGreen.withValues(
                        alpha: 0.4,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8),
                      ),
                      elevation: 0,
                    ),
                    child: isLoading
                        ? const CircularProgressIndicator(color: Colors.white)
                        : const Text(
                            'Sign Up',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 18,
                              fontWeight: FontWeight.w500,
                            ),
                          ),
                  ),
                ),

                const SizedBox(height: 20),

                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text(
                      'Already have an account? ',
                      style: TextStyle(
                        color: AppColors.textGrey,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    GestureDetector(
                      onTap: () => Navigator.pop(context),
                      child: const Text(
                        'Log In',
                        style: TextStyle(
                          color: AppColors.brandGreen,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ],
                ),

                const SizedBox(height: 30),
              ],
            ),
          ),
        ),
      ),
    );
  }

  // Live checklist of unmet password requirements. Each line disappears as
  // soon as it's satisfied, and the whole checklist hides once all are met.
  Widget _buildPasswordChecklist() {
    final password = passwordController.text;
    if (password.isEmpty) return const SizedBox.shrink();

    final requirements = <String, bool>{
      'At least 8 characters': _hasMinLength(password),
      'An uppercase letter': _hasUpper(password),
      'A lowercase letter': _hasLower(password),
      'A number': _hasDigit(password),
      'A special character': _hasSpecial(password),
    };

    final allMet = requirements.values.every((met) => met);
    if (allMet) return const SizedBox.shrink();

    return Padding(
      padding: const EdgeInsets.only(top: 6, left: 4),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: requirements.entries.map((entry) {
          final met = entry.value;
          return Padding(
            padding: const EdgeInsets.only(bottom: 2),
            child: Row(
              children: [
                Icon(
                  met ? Icons.check_circle : Icons.circle_outlined,
                  size: 14,
                  color: met ? AppColors.brandGreen : AppColors.textGrey,
                ),
                const SizedBox(width: 6),
                Text(
                  entry.key,
                  style: TextStyle(
                    fontSize: 12,
                    color: met ? AppColors.brandGreen : AppColors.textGrey,
                  ),
                ),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }

  // Hint below confirm password; only shown while it doesn't match yet,
  // disappears once the passwords match.
  Widget _buildConfirmHint() {
    final password = passwordController.text;
    final confirm = confirmController.text;
    if (confirm.isEmpty || confirm == password) {
      return const SizedBox.shrink();
    }

    return const Padding(
      padding: EdgeInsets.only(top: 5, left: 4),
      child: Text(
        'Passwords do not match',
        style: TextStyle(color: AppColors.errorRed, fontSize: 12),
      ),
    );
  }

  // Checkbox row with tappable Terms/Privacy links that open placeholder dialogs.
  Widget _buildTermsCheckbox() {
    final hasError = _termsError != null;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(
              height: 24,
              width: 24,
              child: Checkbox(
                value: agreedToTerms,
                activeColor: AppColors.brandGreen,
                onChanged: (value) {
                  setState(() {
                    agreedToTerms = value ?? false;
                    if (agreedToTerms) _termsError = null;
                  });
                },
              ),
            ),
            const SizedBox(width: 10),
            Expanded(
              child: Wrap(
                crossAxisAlignment: WrapCrossAlignment.center,
                children: [
                  const Text(
                    'I agree to the ',
                    style: TextStyle(color: AppColors.textGrey),
                  ),
                  GestureDetector(
                    onTap: () => _showLegalDialog(
                      'Terms of Service',
                      _termsOfServiceText,
                    ),
                    child: const Text(
                      'Terms of Service',
                      style: TextStyle(
                        color: AppColors.brandGreen,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                  const Text(
                    ' and ',
                    style: TextStyle(color: AppColors.textGrey),
                  ),
                  GestureDetector(
                    onTap: () =>
                        _showLegalDialog('Privacy Policy', _privacyPolicyText),
                    child: const Text(
                      'Privacy Policy',
                      style: TextStyle(
                        color: AppColors.brandGreen,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
        if (hasError)
          Padding(
            padding: const EdgeInsets.only(top: 4, left: 34),
            child: Text(
              _termsError!,
              style: const TextStyle(color: AppColors.errorRed, fontSize: 12),
            ),
          ),
      ],
    );
  }

  @override
  void dispose() {
    fullNameController.dispose();
    emailController.dispose();
    passwordController.dispose();
    confirmController.dispose();
    super.dispose();
  }
}
