import 'package:flutter/material.dart';

import '../core/app_info.dart';
import '../widgets/app_top_bar.dart';

class HelpAboutScreen extends StatelessWidget {
  const HelpAboutScreen({super.key});

  static const Color _primaryColor = Color(0xFF2E7D32);
  static const Color _darkText = Color(0xFF1E293B);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8FAF8),
      extendBodyBehindAppBar: true,
      appBar: const AppTopBar(
        title: 'Help & About',
        description: 'App information and support',
        showProfile: false,
        showBack: true,
      ),

      body: SingleChildScrollView(
        physics: const BouncingScrollPhysics(),
        padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(
              height:
                  MediaQuery.of(context).padding.top + AppTopBar.height + 20,
            ),

            // --- App Identity ---
            Center(
              child: Column(
                children: [
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: _primaryColor.withValues(alpha: 0.08),
                      shape: BoxShape.circle,
                    ),
                    child: const Icon(
                      Icons.eco_rounded,
                      size: 36,
                      color: _primaryColor,
                    ),
                  ),
                  const SizedBox(height: 12),
                  const Text(
                    AppInfo.name,
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.w800,
                      color: _darkText,
                      letterSpacing: -0.3,
                    ),
                  ),
                  const SizedBox(height: 2),
                  Text(
                    'Version ${AppInfo.version}',
                    style: TextStyle(
                      fontSize: 13,
                      color: Colors.grey.shade600,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 28),

            _buildSectionTitle('About'),
            _buildCard(
              'MaisNutri detects and classifies nutrient deficiencies in corn '
              'leaves from a photo, then suggests a fertilizer based on the '
              'deficiency it identifies.',
            ),
            const SizedBox(height: 20),

            _buildSectionTitle('How to Scan'),
            _buildCard(
              'Take the photo in good natural light, focus on the middle '
              'leaves, and fill the frame with a single leaf. Avoid blurry '
              'shots, deep shadows, and wet leaves.',
            ),
            const SizedBox(height: 20),

            _buildSectionTitle('Disclaimer'),
            _buildCard(
              'Detections and fertilizer recommendations are generated by an '
              'automated model and are intended to support, not replace, '
              'professional agricultural advice.',
            ),

            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Text(
        text,
        style: const TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.bold,
          color: _darkText,
          letterSpacing: -0.3,
        ),
      ),
    );
  }

  Widget _buildCard(String body) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border.all(color: Colors.grey.shade100),
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Text(
        body,
        style: TextStyle(
          fontSize: 13,
          color: Colors.grey.shade700,
          height: 1.5,
        ),
      ),
    );
  }
}
