import 'package:flutter/material.dart';

import '../core/app_info.dart';
import '../core/colors.dart';
import '../widgets/app_top_bar.dart';
import '../widgets/brand_wordmark.dart';
import '../widgets/page_heading.dart';

class HelpAboutScreen extends StatelessWidget {
  const HelpAboutScreen({super.key});

  static const List<String> _scanSteps = [
    'Take the photo in good natural light.',
    'Focus on the middle leaves of the plant.',
    'Fill the frame with a single leaf.',
    'Avoid blurry shots, deep shadows and wet leaves.',
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: const AppTopBar(showProfile: false, showBack: true),
      body: ListView(
        physics: const BouncingScrollPhysics(),
        padding: EdgeInsets.fromLTRB(
          20,
          MediaQuery.of(context).padding.top + AppTopBar.height + 8,
          20,
          32,
        ),
        children: [
          const PageHeading(kicker: 'Support', title: 'Help & about'),
          _buildCard(
            child: Row(
              children: [
                Image.asset('assets/images/logo.png', height: 56),
                const SizedBox(width: 12),
                const Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    BrandWordmark(fontSize: 22),
                    SizedBox(height: 2),
                    Text(
                      'Version ${AppInfo.version}',
                      style: TextStyle(
                        fontSize: 13,
                        color: AppColors.textMuted,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          const SectionTitle('About'),
          _buildCard(
            child: const Text(
              'MaisNutri detects and classifies nutrient deficiencies in corn '
              'leaves from a photo, then suggests a fertilizer based on the '
              'deficiency it identifies.',
              style: _bodyStyle,
            ),
          ),
          const SectionTitle('How to scan'),
          _buildCard(
            child: Column(
              children: [
                for (var i = 0; i < _scanSteps.length; i++)
                  Padding(
                    padding: EdgeInsets.only(
                      bottom: i == _scanSteps.length - 1 ? 0 : 12,
                    ),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Container(
                          width: 24,
                          height: 24,
                          alignment: Alignment.center,
                          decoration: const BoxDecoration(
                            color: AppColors.corn,
                            shape: BoxShape.circle,
                          ),
                          child: Text(
                            '${i + 1}',
                            style: const TextStyle(
                              fontFamily: AppFonts.display,
                              fontSize: 13,
                              fontWeight: FontWeight.w800,
                              color: AppColors.textDark,
                            ),
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Padding(
                            padding: const EdgeInsets.only(top: 2),
                            child: Text(_scanSteps[i], style: _bodyStyle),
                          ),
                        ),
                      ],
                    ),
                  ),
              ],
            ),
          ),
          const SectionTitle('Disclaimer'),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: AppColors.corn.withValues(alpha: 0.18),
              borderRadius: BorderRadius.circular(18),
            ),
            child: const Text(
              'Detections and fertilizer recommendations are generated by an '
              'automated model and are intended to support, not replace, '
              'professional agricultural advice.',
              style: _bodyStyle,
            ),
          ),
        ],
      ),
    );
  }

  static const TextStyle _bodyStyle = TextStyle(
    fontSize: 14,
    height: 1.5,
    color: AppColors.textDark,
  );

  Widget _buildCard({required Widget child}) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppColors.card,
        border: Border.all(color: AppColors.border),
        borderRadius: BorderRadius.circular(18),
      ),
      child: child,
    );
  }
}
